name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    uses: sanzenwin/workflows/.github/workflows/npm-release-publish.yml@main
    permissions:
      contents: write
    secrets: inherit
